# General properties
quarkus:
  http:
    port: ${HTTP_PORT:8080}
  rest:
        path: /api
  log:
    level: ${LOG_LEVEL:INFO}
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      level: ${LOG_LEVEL:DEBUG}
    file:
      enable: true
      path: "logs/store-back.log"
      json: true
      level: ${LOG_LEVEL:INFO}
    category:
      "org.ormi.priv.tfa.orderflow.store":
        level: ${LOG_LEVEL:DEBUG}
  rest-client:
    product-registry-api:
      url: ${PRODUCT_REGISTRY_URL:http://localhost:8091/api}
    product-registry-read-api:
      url: ${PRODUCT_REGISTRY_READ_URL:http://localhost:8092/api}